### ISSUE TITLE
能否让Vercel保持为最新的master

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#1]
Vercel app现在还停留在很早的 https://github.com/LibreService/my_rime/commit/bb2159fb38f21e66490edfa73f2d6ffd2ac9f97d ，还只有朙月拼音一个而案。是否能让GitHub Action自动更新Vercel app？

以及，我注意到最近的一些commits都是在添加各方案，未来会支持在线部署吗？或者，如果用WASM在线部署有难度的话，是否可以提供更详细的本地部署指南，比如浏览器中使用本地编译出来的build文件，或者干脆就是在编译此项目的时候加入自定义方案的build文件，最终分发出一个dist这种的。

**Comment by eagleoflqj** [comment]
目前资源文件超过100MB，vercel有100G/30天的流量限制，都传上去烧得速度会比较快。解决方案是传到npm上用不限流量的jsdelivr CDN加载，但是这个体积对单个npm包来说还是太大了，我打算一个输入法家族一个包，拆包/上传/加载的代码不久就会搞，那时候vercel就可以和GitHub Actions同步了。
如果想现在就体验或者部署的话，README给了个新鲜产物下载链接，你想自行部署到哪里都可以。

在线部署理论上是可行的，但是鉴于比较影响用户体验（本地部署都有人嫌慢，wasm又会慢上几倍），我想做但不想最近做（PR welcome）。本地部署自定义方案跟rime官方方案没有区别，只要你适配了plum，就可以替掉schemas.json然后执行构建流程。详细文档待我测试几个第三方方案后会写。

**Comment by bczhc** [comment]
好的好的，目前我就是下载的GitHub Action的artifacts。期待这个项目。之后我也尝试研究下手动给这个项目添加方案。

**Comment by eagleoflqj** [comment]
最新版全方案上线咯

**Comment by eagleoflqj** [comment]
定制文档也有了https://github.com/LibreService/my_rime/blob/master/doc/customize.md
