### ISSUE TITLE
新的问题

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#10]
1. 我的方案配置中有一句：

   ```yaml
    - { accept: space, send: Escape, when: composing } #无候选时（空码）空格清屏
   ```

   期待是空码时按空格清除空码，无任何其他操作。但是实际它会清码后再上一个空格。按空格时控制台写的是`simulate key sequence:  `。我开了`debug=on`，发送`apo `（`apo`为空码），就会出现多上一个空格的问题；但发送`apo{space}`，就正常。看来应该得向librime传`{space}`。

1. Tab键不映射
   
   ```yaml
       - { accept: Tab, send: apostrophe, when: always }
       - { accept: Release+Tab, send: Release+apostrophe, when: always }
   ```
   
1. 左右Alt不映射

   ```yaml
       - { when: has_menu, accept: Alt_R, send: 3 } # 三选
       - { when: has_menu, accept: Alt_L, send: 4 } # 四选
   ```

1. dependencies都得在schemas.json中定义出来，这就导致它们都会在方案列表中显现出来，即使它们并不是实际使用的方案。就像这样，那些没中文名的就是辅助方案：

   ![image](https://user-images.githubusercontent.com/49330580/225572130-9c124060-96a0-4749-8959-1737ed54cc15.png)

**Comment by bczhc** [comment]
以及感谢对lua的支持！现在我的方案终于能用了，基本所有功能都是正常的，就是上面测试的几个问题。超过我的预想。没想到竟还有环境变量hh
![image](https://user-images.githubusercontent.com/49330580/225573736-489ab171-3a25-41e9-a205-1ce2b6920f83.png)

**Comment by bczhc** [comment]
哦还有，我的emoji引导不知道为什么不编码提示了。就emoji引导不行，其他的都可以。
![Peek](https://user-images.githubusercontent.com/49330580/225581240-18d70528-dfb5-4967-97c4-e754c3c6bed0.gif)
![Peek 2023-03-16 17-54](https://user-images.githubusercontent.com/49330580/225581037-d7b50d54-1fb2-4226-8718-c8dd260037bf.gif)

**Comment by bczhc** [comment]
我这个方案可能有些复杂。不知其他过多不相关的东西会不会影响到。
```json
[
  {
    "id": "luna_pinyin",
    "name": "朙月拼音",
    "emoji": true,
    "target": "luna-pinyin",
    "dependencies": ["stroke"],
    "license": "LGPL-3.0-only"
  },
  {
    "id": "stroke",
    "name": "五笔画",
    "target": "stroke",
    "dependencies": ["luna_pinyin"],
    "variants": [],
    "license": "LGPL-3.0-only"
  },
  {
    "id": "tiger",
    "name": "虎码",
    "target": "bczhc/rime-demo",
    "dependencies": [
      "tiger_core2022",
      "PY_c",
      "emoji",
      "html_chars",
      "latin_international",
      "ipa_yunlong",
      "short_punct",
      "named_ipa_diacritics"
    ]
  },
  {
    "id": "tiger_guihu",
    "name": "九重鬼虎",
    "target": "bczhc/rime-demo",
    "dependencies": [
      "tiger_core2022",
      "PY_c",
      "emoji",
      "html_chars",
      "latin_international",
      "ipa_yunlong",
      "short_punct",
      "named_ipa_diacritics"
    ]
  },
  {
    "id": "zrm_pinyin",
    "name": "自然码+辅助码",
    "target": "bczhc/rime-demo",
    "dependencies": ["chaizi"]
  },
  {
    "id": "kongmingma",
    "name": "空明码",
    "target": "bczhc/rime-demo",
    "dependencies": []
  },
  {
    "id": "tiger_core2022",
    "name": "tiger_core2022",
    "target": "bczhc/rime-demo",
    "dependencies": []
  },
  {
    "id": "PY_c",
    "name": "PY_c",
    "target": "bczhc/rime-demo",
    "dependencies": ["stroke"]
  },
  {
    "id": "emoji",
    "name": "emoji",
    "target": "bczhc/rime-demo",
    "dependencies": []
  },
  {
    "id": "html_chars",
    "name": "html_chars",
    "target": "bczhc/rime-demo",
    "dependencies": []
  },
  {
    "id": "latin_international",
    "name": "latin_international",
    "target": "bczhc/rime-demo",
    "dependencies": []
  },
  {
    "id": "ipa_yunlong",
    "name": "ipa_yunlong",
    "target": "bczhc/rime-demo",
    "dependencies": ["named_ipa_diacritics"]
  },
  {
    "id": "short_punct",
    "name": "short_punct",
    "target": "bczhc/rime-demo",
    "dependencies": []
  },
  {
    "id": "named_ipa_diacritics",
    "name": "named_ipa_diacritics",
    "target": "bczhc/rime-demo",
    "dependencies": []
  },
  {
    "id": "chaizi",
    "name": "chaizi",
    "target": "bczhc/rime-demo",
    "dependencies": []
  }
]
```

**Comment by bczhc** [comment]
左右Alt是在这个地方return掉了，但不是按这里说的，在edit模式下会发送所有keydown。我没办法让它simulate左右Alt。所谓的edit模式是什么？

https://github.com/LibreService/my_rime/blob/6e8da576f4e0e059807904cb0a979f0c1fe36ee2/src/components/MyPanel.vue#L222-L232

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/b754aa572f118a8f192d7fc03c59e99676f3ac25 修复了emoji的问题。在我集成emoji时`tips: none`还不是默认（这个[commit](https://github.com/rime/rime-emoji/commit/618b9a5b8224b7742fb92398f8aecfed01b58b1b)改的），导致每个emoji后面都有文字https://github.com/rime/rime-emoji/issues/24#issue-807143014 ，于是我把emoji后面的comment全屏蔽了。现在默认显示所有comment，提供了`hideComment: "emoji"`专门屏蔽emoji的comment。

**Comment by eagleoflqj** [comment]
edit模式是我自造的，就是指候选词popover弹出来的状态。
https://github.com/LibreService/my_rime/commit/ebb8a497bafb69cd31ce31949c9f51a8e3a424d2 支持了左右Alt键，因为是edit模式，所以是在你找的代码块后边。

**Comment by eagleoflqj** [comment]
非edit模式下，Tab有明确的转移焦点的默认行为，所以不支持。你可以改代码强行支持。
在`onKeydown`打一个断点，然后按Tab键，单步执行，就会发现是https://github.com/LibreService/my_rime/blob/ebb8a497bafb69cd31ce31949c9f51a8e3a424d2/src/components/MyPanel.vue#L228 走的默认行为，于是可以把上一行的条件改成`document.activeElement !== textarea || (!isPrintableKey && key !== 'Tab')`，就可以把Tab也交给librime。
类似的操作也可以在`onKeyup`搞一遍，结果是把https://github.com/LibreService/my_rime/blob/ebb8a497bafb69cd31ce31949c9f51a8e3a424d2/src/components/MyPanel.vue#L286 改成`editing.value && (isPrintable(key) || key === 'Tab'`

**Comment by bczhc** [comment]
好吧，既然
> keydown的handler是异步的（因为我让librime跑在worker线程），在第一个await之前必须决定是否prevendDefault，所以只要让librime处理就不可能走默认行为了。

的话，那就只能没法处理非composing模式下的Tab了。

就是在composing模式下，Release+Tab好像没处理。处理下这个就好了。

**Comment by eagleoflqj** [comment]
> 就是在composing模式下，Release+Tab好像没处理。处理下这个就好了。

可以，https://github.com/LibreService/my_rime/commit/5c14af4c6af9bc51127925b9faded176cb3ee2ec 处理了。当时过滤是因为`onKeyup`只是为了宫保拼音加的，没考虑定制需求。

**Comment by bczhc** [comment]
1的话我用`KeySequence::Parse`空格字符和`{space}`，效果是一样的。所以问题应该不是发送`{space}`和` `之前的区别。

debug on之后，比如那个虎码的`cpo`是空码，我在下面发送key的地方输入`cpo`回车，再输单一一个空格，再回车，这时上方文本框会多出一个空格，非预期行为；但我如果一次性输入`cpo_`（_是空格），回车，上方不会上那多的一个空格。

不表达那么多，简明的测试例子就是：

`a_cpo_b_` -> `来如`

但`a_cpo`, `_`, `b _ -> `来 如`

它们俩应是一样的，即`来如`

**Comment by bczhc** [comment]
空格是在这里上屏的：
https://github.com/LibreService/my_rime/blob/5c14af4c6af9bc51127925b9faded176cb3ee2ec/src/components/MyPanel.vue#L162-L168

写着REJECTED，但事实上这里空格应该是被消费的，也就是`RimeProcessKey`会返回True，所以这里不应该来到这个if分支。

我不太懂Emscripten WASM和前端，似乎没看到`Module.ccall('process', ...`相应的C函数？而且rime_api好像也并没有一个叫`process`的函数吧。本来就是想看一下这个`process`的返回值是哪里构建的，据我看的librime源码，`RimeSimulateKeySequence`好像不能直接从它的返回值得知是否被processors消费掉，741行的返回值并没有使用，返回False只是代表着Parse失败：
https://github.com/rime/librime/blob/d0d227c70daa25c9671e8355b042c0c1697c2de4/src/rime_api.cc#L730-L744

只有`RimeProcessKey`可以反映出：
https://github.com/rime/librime/blob/d0d227c70daa25c9671e8355b042c0c1697c2de4/src/rime/engine.cc#L96-L115

**Comment by eagleoflqj** [comment]
`process`定义在https://github.com/LibreService/my_rime/blob/5c14af4c6af9bc51127925b9faded176cb3ee2ec/src/workerAPI.ts#L7
到这里还是在主线程。我把worker通信逻辑（postMessage）封装在了https://github.com/LibreService/my_worker

然后这里就已经是worker线程了https://github.com/LibreService/my_rime/blob/5c14af4c6af9bc51127925b9faded176cb3ee2ec/src/worker.ts#L91-L93
ccall能调的函数要么是被`EMSCRIPTEN_KEEPALIVE`修饰，要么是在emcc/em++时显式export https://github.com/LibreService/my_rime/blob/5c14af4c6af9bc51127925b9faded176cb3ee2ec/scripts/build_wasm.mjs#L38

最终找到https://github.com/LibreService/my_rime/blob/master/wasm/api.cpp，封装了librime，把结果以json形式传给前端。

**Comment by bczhc** [comment]
哦看到了。刚才IDEA发毛病了，全局搜索没搜到。似乎不应以是否commit了来判断key event是否被消费掉？

我也试着写了个rime-tui，就是用的之前我说的，如果processors没处理再执行默认行为。用的就是`RimeProcessKey`。没有问题。
https://github.com/bczhc/rime-tui/blob/cc5c7894c48bf8fe4b15fe49c962bb5f8c9948e2/src/main.rs#L85-L99
https://github.com/bczhc/librime-rs/blob/8b745820b8b28d7a007f436605f3bcc882ede72e/src/lib.rs#L129-L132

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/ba8173266b87e67c24d09a256fe0f3c3067702a4 解决了。我本来打算在前端搞，然后发现你说的对，这其实是后端没能区分是透传还是丢弃。但是rime api没开我要的口子（既parse又给process返回值），我就用上一步有没有pre edit来区分了。反正测试都在，要是还有特殊情况我再想办法。
