### ISSUE TITLE
粵語拼音支持簡體中文

### ISSUE THREAD

**Issue by YLJ77** [LibreService/my_rime#11]
係方案選單設定中無找到簡體中文切換嘅選項，希望可以支持簡體中文輸入

**Comment by eagleoflqj** [comment]
rime-cantonese里[定义](https://github.com/rime/rime-cantonese/blob/62b4a51d7a17b1bc60ee32b27bf8ae6aa017396b/jyut6ping3.schema.yaml#L37-L38)的繁、港、台、简都是支持的，默认即为简体，通过这个`中`右边的`简`按钮切换。
![Screenshot from 2023-03-26 22-24-38](https://user-images.githubusercontent.com/26783539/227825775-ec0acd8b-4f60-443f-90e4-033d0abeba33.png)
