### ISSUE TITLE
支持`alternative_select_labels`和`page_size`

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#12]
现在写在*.custom.yaml里面的好像不会生效。

https://github.com/bczhc/rime-config/blob/9fcdb365888ea475f48486e44f04dcb58b1ede81/092wubi.custom.yaml#L1-L6

**Comment by eagleoflqj** [comment]
明白了，这个是plum的问题，它故意不安装*.custom.yaml https://github.com/rime/plum/blob/6f502ff6fa87789847fa18200415318e705bffa4/scripts/install-packages.sh#L74
所以你得自己把它们复制到build/librime_native/bin再`pnpm run schema`了，我试了一下是可行的
![Screenshot from 2023-06-01 18-47-32](https://github.com/LibreService/my_rime/assets/26783539/c6314344-c5e9-40c9-99e7-6de0bdab8878)
