### ISSUE TITLE
Font

### ISSUE THREAD

**Issue by groverlynn** [LibreService/my_rime#15]
Ubuntu的默認中文字體應該是文泉驛微米黑，而不是Noto Sans。
windows繁中的字體應當爲「微軟正黑Microsoft JhengHei」。繁中系統沒有「微軟雅黑」字體。
mac的默認中文字體「蘋方」分簡SC、繁TC、港HK三個版本，最好能遵從用戶系統的語言優先順序。

unihan擴展區B-F的字體推薦用[一點明體](https://github.com/ichitenfont/I.Ming)取代萬年不更新的花園明朝

**Comment by eagleoflqj** [comment]
> Ubuntu的默認中文字體應該是文泉驛微米黑，而不是Noto Sans。

根据`/etc/fonts/conf.d/64-language-selector-prefer.conf`列出的字体，是Noto Sans无误。我的Ubuntu版本23.04，为排除我之前自己操作过字体，又检查了一下Ubuntu 20.04的虚拟机，也是没有安装`fonts-wqy-*`软件包，而有自动安装的`fonts-noto-*`。

> windows繁中的字體應當爲「微軟正黑Microsoft JhengHei」
> mac的默認中文字體「蘋方」分簡SC、繁TC、港HK三個版本，最好能遵從用戶系統的語言優先順序。

可以改，我去查查浏览器获取locale的API。

> unihan擴展區B-F的字體推薦用[一點明體](https://github.com/ichitenfont/I.Ming)取代萬年不更新的花園明朝

可以加，取代就算了，个人感觉花园明朝知名度更高，反正都是可选的。

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/2b94f772f5126c37e816c6227073796a9f1ae063 已解决

**Comment by groverlynn** [comment]
> > Ubuntu的默認中文字體應該是文泉驛微米黑，而不是Noto Sans。
> 
> 根据`/etc/fonts/conf.d/64-language-selector-prefer.conf`列出的字体，是Noto Sans无误。我的Ubuntu版本23.04，为排除我之前自己操作过字体，又检查了一下Ubuntu 20.04的虚拟机，也是没有安装`fonts-wqy-*`软件包，而有自动安装的`fonts-noto-*`。
> 
> > windows繁中的字體應當爲「微軟正黑Microsoft JhengHei」
> > mac的默認中文字體「蘋方」分簡SC、繁TC、港HK三個版本，最好能遵從用戶系統的語言優先順序。
> 
> 可以改，我去查查浏览器获取locale的API。
> 
> > unihan擴展區B-F的字體推薦用[一點明體](https://github.com/ichitenfont/I.Ming)取代萬年不更新的花園明朝
> 
> 可以加，取代就算了，个人感觉花园明朝知名度更高，反正都是可选的。并且一点明朝+遍黑体不能取代花园明朝，比如𠂓𤓰。

一點明體沒收錄的漢字，基本可以肯定是錯字，以V源的喃字為主。Unihan／Unicode正在把V源漢字全部推倒重來。而像是「𤓰」，到底是「瓜」的錯字還是「爪」的錯字都説不清，但一定是錯字，按照現在的標準是不應該收錄的。unicode 11至16版新增的漢字，花園明朝都是沒有的。
