### ISSUE TITLE
artifact 中未生成 reverse.bin 和 table.bin

### ISSUE THREAD

**Issue by amorphobia** [LibreService/my_rime#16]
由于没有完整的 linux 环境，我的所有 build 都是用 github actions 完成的

|commit|action|
|---|---|
|[8c190fd](https://github.com/amorphobia/jd-web/commit/8c190fda54122b93df00eaaa31e4b69231976d46)|[#15](https://github.com/amorphobia/jd-web/actions/runs/5516915550)|

```bash
$ tree dist/ime/amorphobia/rime-jiandao@release/
dist/ime/amorphobia/rime-jiandao@release/
├── jiandao.prism.bin
├── jiandao.schema.yaml
└── package.json
```

在 WSL ubuntu 里运行 dist 下的 `rime_console` 会 segmentation fault，而 `rime_deployer --build` 或者 `rime_api_console` 则正常生成。

但我尝试把 `install_schemas.mjs` 里的命令换成 `./rime_deployer --build` 后（commit [8be0bd2](https://github.com/amorphobia/jd-web/commit/8be0bd29bcc70f8cd52eb43b867f72e7b77bfe53)），依然无法生成 `reverse.bin` 和 `table.bin`（action [#16](https://github.com/amorphobia/jd-web/actions/runs/5517073593)）。

另外，在线使用 micro plum 部署是正常的，或者[手动补全](https://github.com/amorphobia/jd-web/commit/6f3080360cfbeb1533d2c728de6b35da53fb8d2f)缺失的 `reverse.bin` 和 `table.bin` 也是可以正常打字的。

**Comment by eagleoflqj** [comment]
其实是生成了的，但因为`install_schemas.mjs`写得有问题，没支持plum repo的branch写法，于是没从`build/librime_native/bin/build`拷到`public/ime/`下面（这个脚本出过的问题实在太多了
我正准备重构离线部署（去plum换micro plum），能顺便修这个bug。

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/bf64783478e86e022fbfc4e1188a095eafef358a 修好了，顺便不再需要把lua相关文件手动放到rime-config了。
