### ISSUE TITLE
改進建議－候選框方向、候選項數量

### ISSUE THREAD

**Issue by cuichungman** [LibreService/my_rime#19]
Qijia 你好，
　　
**【候選框方向及候選項數量】**
![候選框](https://github.com/LibreService/my_rime/assets/16935971/e1c4aab6-b680-4000-9c6d-c34b73c1b432)
補充一下對候選字詞顯示方式嘅反饋。目前 My Rime 嘅候選框為橫向、只能顯示五個候選項，限制咗選字嘅流暢度。呢層，希望作者提供**以橫／豎向顯示候選框**及**可選高達十個候選項（用 1 至 0 鍵選取）**，以允許用户按需調節。
　　
之前反饋中嘅【記錄用户設定】亦希望可應用於此選項上。
　　
　　
秋安，
　　
ＣＨＵＮＧ

**Comment by eagleoflqj** [comment]
可以，会提供一个checkbox强制竖排，以及一个下拉菜单设定选项个数，并记录这两项。

**Comment by cuichungman** [comment]
感謝大大接納　🤗

**Comment by eagleoflqj** [comment]
Fixed by 1c86554baa0ca101f0975fd085f147751e195742 and 5bc23f9a7392025c62cc6cbe1b98232221f05918
