### ISSUE TITLE
改進建議 - 記錄用戶設定、提升被搜尋引擎搵到嘅效率

### ISSUE THREAD

**Issue by cuichungman** [LibreService/my_rime#2]
你好 Qijia，

多謝作者辛勤勞動推出 rime 線上版本。貴功能對我廣大不諳電腦嘅人民群眾嚟講實屬福音。以前我哋喺新機（尤其是喺 Windows 上）要設定粵語輸入法可謂難關重重。如今有咗作者嘅關懷，快速調用 rime 輸入法唔再係難事。惟使用過程中，遇到兩個不便之處，有望作者將之改善。

<img width="860" alt="螢幕截圖 2023-02-25 下午11 20 55" src="https://user-images.githubusercontent.com/16935971/221397736-81424683-dba4-444d-8d21-3e6a4e38a6b9.png">

**一、輸入法未能記錄用戶設定。如今 My Rime 未能記住訪問者嘅輸入法設定，每次重新進入皆需再次設定。期望作者令輸入法記住用戶最後一次使用嘅設定；**

**二、輸入法仍難以被各搜尋器所搜尋。如今貴功能難以為用戶所搜尋，記住「 https://my-rime.vercel.app 」亦頗為困難，喺離開網頁或使用新裝置時，用戶可能會難以將其搵返出嚟。故期望作者考慮提升頁面可被搜尋器搵到嘅機會，令用家以例如「rime」「rime online」「粵語打字」「粵語輸入法」「Cantonese Input Online」等字眼均可搵到 My Rime。**

望作者考慮上述建議。無論如何，仍再次感謝作者嘅付出及貢獻。

即頌春祺，
CHUNG

**Comment by eagleoflqj** [comment]
点一下输入框下面第三个按钮可以复制当前的设定对应的URL，可以加进收藏夹。
03672893bac8ad92f02055b8a30369ec8044c780 实现了你想要的记住使用设定的功能。

域名不好记我也没有办法，免费嘛，没什么选择余地。我倒是可以请求RIME网站加个友情链接。
针对你的case，可以利用Microsoft/Google/Firefox账号的同步收藏夹功能。
SEO方面我不是专家，搜索引擎怎么收录也不是我说了算；不过你的建议很好，https://github.com/LibreService/my_rime/commit/6713f50cfa7807fee23041d5ac51527eaf4999c4 增加了几个关键词。
