### ISSUE TITLE
Missing text for librime BSD license

### ISSUE THREAD

**Issue by alex-kinokon** [LibreService/my_rime#20]
Upstream librime is distributed under a BSD license, which requires reproducing the copyright notice verbatim in both source code and binary form. Both the repo and the website [should mention](https://www.gnu.org/licenses/license-compatibility.en.html) the upstream license.

**Comment by eagleoflqj** [comment]
Both README and website have link pointing back to librime. Both source and binary form are distributed through network, so nothing prevents end users to know what upstream libraries are used and what licenses apply.
