### ISSUE TITLE
支持「声笔」打字方案

### ISSUE THREAD

**Issue by isPoto** [LibreService/my_rime#21]
声笔有修改Rime内核，声笔共有6个方案。希望能支持声笔方案

https://github.com/sbxlmdsl/librime

**Comment by eagleoflqj** [comment]
本项目无法支持librime的fork，因为目标是一直追着librime master，而fork代码难以管理。
可以整理一下改动pr到librime，或者fork本项目自行构建。对于后者，建议先在本地跑通本构建流程（3大桌面都支持但建议Ubuntu），然后把librime的submodule改掉，调整librime_patch，再重新构建。
Not planned，但是遇到构建问题可以继续在下面讨论或者来https://discord.gg/gq4c9ufZkX

**Comment by eagleoflqj** [comment]
https://github.com/tansongchen/my_rime/tree/sbxlm
