### ISSUE TITLE
用到`ReverseDb`的都无效了

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#25]
目前rime中只能利用反查数据库构造可在lua中手动查表的方法。

一个应用例子，从一个字符查到一个标点符号：

- lua：https://github.com/bczhc/rime-config/blob/ac3aef615cdb74fe1407ecf566c86afa5e3bac2c/lua/short_punct_pre_speller_processor.lua#L105-L110
- 表：https://github.com/bczhc/rime-config/blob/master/short_punct.dict.yaml

**Comment by eagleoflqj** [comment]
It's because you haven't deployed `short_punct`.
My test procedure is:
* Use Micro Plum to download `092wubi.schema.yaml` and `short_punct.schema.yaml`.
* Deploy **both** so that you can see `short_punct.reverse.bin` under `/rime/build`.
* Select `五笔` and press `zf`, see `“` committed.
