### ISSUE TITLE
构建问题：卡在`pnpm run schema`

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#3]
在这里卡了好几分种了。![image](https://user-images.githubusercontent.com/49330580/221397770-2d14283b-204b-40f5-8bbe-bb1062f194f3.png)不知道为什么。网络是通过`http_proxy`和`https_proxy`设置的代理，应该不成问题。

在随后的构建中就会出现：
```console
~/open-source/my_rime master ❯ pnpm run wasm                                                          3m 2s 15:33:06

> @libreservice/my-rime@0.2.0 wasm /home/bczhc/open-source/my_rime
> bash scripts/build_wasm.sh

error: build/sysroot/usr/local/share/opencc/t2hkf.json@/usr/local/share/opencc/t2hkf.json does not exist
```

系统：Archlinux 6.1.12

顺便再提供个Dockerfile就好了。

**Comment by bczhc** [comment]
我在Debian Docker容器（来自Dockerhub `node`）中试了，也是这样。

**Comment by bczhc** [comment]
把schemas.json里删掉一些，又等了好久`pnpm run schema`倒是可以完成了。但`pnpm run dev`之后浏览器中报错：
![image](https://user-images.githubusercontent.com/49330580/221403247-add74f80-d4e5-436d-ad2a-21930f8d72d5.png)

**Comment by bczhc** [comment]
测试了，`pnpm run schema`可以完成，但是需要的时间非常久（可能有一个小时）。其中是有什么下载任务吗，如果有的话会不会是代理的问题，比如不感知`http_proxy`和`https_proxy`。希望能够优化。

**Comment by eagleoflqj** [comment]
问题不少，一个一个来
`pnpm run schema`用plum装了几个基础包和schemas.json里提到的所有包。我感觉是这一步没respect shell的代理设置
https://github.com/LibreService/my_rime/blob/a3b46d4d7d3d69c35f464174357cbab34b19c27a/scripts/install_schemas.mjs#L19
spawnSync默认把子进程的stdout和stderr吃了，https://github.com/LibreService/my_rime/commit/a3b46d4d7d3d69c35f464174357cbab34b19c27a 把它们显示出来方便debug

**Comment by bczhc** [comment]
继承了STDOUT倒也没有什么特别有用的输出。不过倒应该却实是代理的问题。继承一下shell的env就可以了。
```patch
diff --git a/scripts/install_schemas.mjs b/scripts/install_schemas.mjs
index 2906384..5f461e8 100644
--- a/scripts/install_schemas.mjs
+++ b/scripts/install_schemas.mjs
@@ -16,10 +16,11 @@ const ids = []
 const rootMap = {}
 
 function install (arg) {
+  let env = process.env
+  env.rime_dir = RIME_DIR
+
   spawnSync('plum/rime-install', [arg], {
-    env: {
-      rime_dir: RIME_DIR
-    }
+    env: env
   })
 }
 ```

**Comment by eagleoflqj** [comment]
继承stdout能确信plum在一个一个慢慢下载😂
https://github.com/LibreService/my_rime/commit/94e26609dc70107c5c82237e08281cdb8d1cd902 修了代理问题

**Comment by eagleoflqj** [comment]
> 把schemas.json里删掉一些，又等了好久`pnpm run schema`倒是可以完成了。但`pnpm run dev`之后浏览器中报错：

很有用的描述信息👍🏻
这个我复现了，是因为一些删掉的输入法是留下来的输入法的依赖，不能删
https://github.com/LibreService/my_rime/commit/f9e8e7cfb99070b6862075bce4cc43030edc548d 在这种情况下给了用户友好的报错

**Comment by eagleoflqj** [comment]
Dockerfile我想用multi-stage build，在node 18的Debian镜像构建，产物放进nginx最新的（数字版本）镜像。有兴趣PR一个吗？不需要用CI测。

**Comment by bczhc** [comment]
好想法。不过我并不太熟悉multi-stage build。。我现在就是只会写个简单Dockerfile，`FROM node`，然后构建步骤用`RUN`串起来，最后产出dist。似乎nginx也不太，在node基镜像上直接安装就可以了吧。

**Comment by eagleoflqj** [comment]
哈哈哈，我也只搞过一次。那就不管nginx了，我可以在你的版本上改

**Comment by bczhc** [comment]
Dockerfile好啦，提了PR。

**Comment by bczhc** [comment]
Issue可关闭了。

**Comment by eagleoflqj** [comment]
其实有了https://github.com/LibreService/my_rime/commit/0bf8d7b08f3390452475c9bc350916b187fd7f88 才算能关，因为没有粤语拼音就不该强制加载t2hkf.json
