### ISSUE TITLE
self hosting blues... need help

### ISSUE THREAD

**Issue by ElTopo** [LibreService/my_rime#33]
Hello, 

I was trying to self host my_rime, but to no avail.

My OS:  Ubuntu 22.04.4 LTS (x86_64), with lighttpd/1.4.63 (ssl) as web server. lighttpd currently has php-cgi enabled and hosts some pages (KeeWeb, rust book from rust lang, and php pages).

Downloaded artifact (https://github.com/LibreService/my_rime/releases/download/latest/my-rime-dist.zip) from README's "self host" section, unzipped it on the Ubuntu system in a folder that /var/www/html has a link to it.

When I accessed https://myserver/my-rime-dist/index.html, I got a page that has "LibreService" / "GitHub", and the the page footer (© 2022-2024 Qijia Liu and contributors, This project is [Free](https://www.gnu.org/philosophy/free-sw) and [Open Source](https://opensource.org/osd) ([AGPLv3](https://www.gnu.org/licenses/agpl-3.0.html)+). 

However, between "My RIME" and "Commit [00e91ad](https://github.com/LibreService/my_rime/commit/00e91ad67914fa945e22e901b711ebc2f965a503) · Built at 5/11/2024, 12:58:52 AM", I only got an empty white area 

The site https://my-rime.vercel.app/ works perfectly in my web browser.

I assume the artifact zip file should have everything I need to host my rime, and my-rime-dist does not need anything else at server side, did I miss anything? or I need to download more packages? Do I need to configure lighttpd the web server?

Thank you.

**Comment by zhou9110** [comment]
Yes, I think that zip file contains everything. 
I have used `npx serve .` to serve `my-rime-dist` locally and it seems fine, so the issue might just related to your web server. 

I guess it mainly because the files are inside a subfolder ( myserver/**my-rime-dist**/index.html ), and the server tries to load the resources from the root folder (like trying to load `https://myserver/worker.js` instead of `https://myserver/my-rime-dist/worker.js`)

**Comment by ElTopo** [comment]
@zhou9110 Thanks.

I actually found the problem.

If my page referred my-rime-dist/index.html directly like this:
`<a href="my-rime-dist/index.html">rime</a>`
I got the blank page problem.

When I changed the link to 
`<a href="my-rime-dist/">rime</a>`
and let the browser loads the default index.html, rime works.
