### ISSUE TITLE
lua扩展支持

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#4]
先问一下。

**Comment by bczhc** [comment]
因为我想尝试把我的输入方案挂这上面，而我那个输入方案高度依赖于lua，没有lua就是用不了的，所以就先问一下……

**Comment by bczhc** [comment]
试了下，好像lua确实还不支持。

**Comment by eagleoflqj** [comment]
是不支持，不过似乎挺有意思的。
查了一下lua有wasm vm，然而我不懂lua，也不知道librime-lua的原理，一时半会儿是搞不成了。
有进展我会更新的。

**Comment by siuze** [comment]
![image](https://user-images.githubusercontent.com/54578647/222956027-09330f4a-b090-4559-ba91-b45cdb295d1f.png)
librime的action里面是放个环境变量进去，使得附带编译librime-lua的

**Comment by eagleoflqj** [comment]
hack了不少地方，不过

![Screenshot from 2023-03-14 22-38-03](https://user-images.githubusercontent.com/26783539/225191055-0b843b79-9df1-47cc-86ff-825d11787ba6.png)

还得整理整理代码

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/6e8da576f4e0e059807904cb0a979f0c1fe36ee2 支持了lua，文档也已更新。
