### ISSUE TITLE
处理组合键

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#6]
比如在schema文件中会定义：
```yaml
- { accept: "Control+p", toggle: pinyin, when: composing }
- { accept: "Control+e", toggle: emoji_cn, when: composing }
````

在使用的时候看控制台里好像并不能向librime发送这样的组合键。而且像Ctrl+p这样的组合键会唤出浏览器的打印窗口，要处理的话就得拦截掉了。

**Comment by eagleoflqj** [comment]
目前对组合键的处理是写死的[白名单](https://github.com/LibreService/my_rime/blob/0bf8d7b08f3390452475c9bc350916b187fd7f88/src/components/MyPanel.vue#L188-L193)。
要支持其他组合键的话，有三个问题：
1. RIME对于按键的定义和浏览器不一样，需要做[映射](https://github.com/LibreService/my_rime/blob/0bf8d7b08f3390452475c9bc350916b187fd7f88/src/components/MyPanel.vue#L47-L60)，这个倒也不用一次找全，case by case处理就行了
2. 如果组合键是切换中英文、繁简、全角等，需要通过librime的callback来通知前端，不然显示就和实际不一致了
3. when: always的组合键如果和浏览器默认行为冲突该怎么办，是不是需要用黑名单，比如Ctrl+x一律不交给librime

**Comment by bczhc** [comment]
2. 是的
3. 焦点在文本框内的时候处理，不在时就让浏览器处理？

**Comment by eagleoflqj** [comment]
怕是不行，比如用户选了一段文字然后Ctrl+x，此时焦点确实也在文本框，但是给了librime就没法使用默认的剪切行为了。

**Comment by bczhc** [comment]
哦哦，没考虑到这个。不过如果真的在配置里定义`when: always`的Ctrl+x，就算是桌面端的rime发行版，也一样就导致Ctrl+x用不了了（不管是中文还是英文模式），会传到librime里去，只有把输入法切掉（Super+空格键），才能不拦截ctrl+x。

**Comment by bczhc** [comment]
所以想法就是，是否应该直管按用户配置文件中定义的去处理，和剪切Ctrl+x的行为冲突了那也没办法，或许那正是用户期待的。

**Comment by bczhc** [comment]
哦，我好像理解了，前端这边好像不太能确定一个组合事件是否应该拦截，困难在这吧。

**Comment by eagleoflqj** [comment]
callback在https://github.com/LibreService/my_rime/commit/980b72eece6a350252b376f6de14283d0a37c588 搞定了，可以开`?debug=on`发`{Control+Shift+2}`测试。不得不说librime给的[demo](https://github.com/rime/librime/blob/d0d227c70daa25c9671e8355b042c0c1697c2de4/tools/rime_api_console.cc)麻雀虽小五脏俱全。
因为改了api.cpp，本地需要重跑`pnpm run wasm`。

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/082524eb62b2b9c2b4d7c01d55e708490df4dbe7 支持了组合键，但是把非编辑状态下的 Control Meta Alt（不带Shift）的组合键屏蔽了。

keydown的handler是异步的（因为我让librime跑在worker线程），在第一个await之前必须决定是否prevendDefault，所以只要让librime处理就不可能走默认行为了。

> processors过一遍之后还没有被处理，那就再模拟出那个按件事件。

太难了，比如Shift+ArrowUp，需要找到最合适的上一行光标位置；以及Control+v需要剪贴板访问权限。

我觉得强行覆盖浏览器默认行为对用户体验打击还是不小的，但要是实在不想要默认行为，可以把这几行干掉，然后定制屏蔽规则。
https://github.com/LibreService/my_rime/blob/082524eb62b2b9c2b4d7c01d55e708490df4dbe7/src/components/MyPanel.vue#L228-L231
