### ISSUE TITLE
似乎资源不是相对引用？

### ISSUE THREAD

**Issue by bczhc** [LibreService/my_rime#7]
我想把dist部署在GitLab page上，就说位置在`https://bczhc.gitlab.io/my_rime-dist`，可当我访问这个地址时，控制台中有以下错误：
![image](https://user-images.githubusercontent.com/49330580/221799373-14231f03-46f1-4051-a8fd-a9b04f8d2a7e.png)

看起来是从服务器根处开始引用的，导致了404错误。比如最后那个请求，期待的是`https://bczhc.gitlab.io/my_rime-dist/LibreService.svg`而不是`https://bczhc.gitlab.io/LibreService.svg`。

**Comment by bczhc** [comment]
还有我注意到当放到子目录中时，Vue router也要改变才能正常工作。这个东西可以更方便地配置吗？

**Comment by eagleoflqj** [comment]
也许可以支持，不过我不清楚PWA在subfolder的行为，至于domain共享的Indexed DB和localStorage就只能假设井水不犯河水了。

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/3e53912caccee4750542be3b589a13b001de9a39 把所有路径都改成相对了
