### ISSUE TITLE
请问怎么编写 schemas.json ？

### ISSUE THREAD

**Issue by xiaobai9978** [LibreService/my_rime#8]
我想添加我自己的方案进去

![image](https://user-images.githubusercontent.com/11792557/222361475-d44e5f54-637e-4979-b729-949eb0b6cfa1.png)

> fatal: 'https://github.com/rime/rime-xiaobai_simp.git/' 鉴权失败
> file:///root/my_rime/scripts/util.mjs:3
>     throw new Error('Command fails.')
>

**Comment by bczhc** [comment]
这是克隆失败了吧。

**Comment by bczhc** [comment]
GitHub已停止HTTPS验证。https://docs.github.com/en/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls

如果克隆的是一个私有仓库，也应用SSH验证。

**Comment by xiaobai9978** [comment]
他克隆的是 https://github.com/rime/rime-xiaobai_simp.git/
我的方案在 https://github.com/xiaobai9978/rime-xiaobai_simp.git/

不是程序员，看这些东西实在有点困难。。

**Comment by bczhc** [comment]
哦，那`target`里应该写`<user>@<repo>`，否则就默认rime/下找了。

https://github.com/rime/plum#advanced-usage

**Comment by xiaobai9978** [comment]
啊了解，感谢，我再去研究研究

**Comment by bczhc** [comment]
抱歉说错了，应该是`user/repo@<branch>`，也就是`xiaobai9978/rime-xiaobai_simp`，branch是master的话就可省略。

**Comment by bczhc** [comment]
另外，我想问下你在添加这个方案的时候还遇到了什么问题吗，我试了这个方案，plum克隆之后`dicts`子目录并没有复制到`build/librime_native/bin`中，导致`build/librime_native/bin/rime_console`运行失败。只能手动复制下那个目录。

**Comment by eagleoflqj** [comment]
感谢指出，确实写得不够清楚，文档已更新。
