### ISSUE TITLE
打不出字，请问是不是不支持小键盘输入？

### ISSUE THREAD

**Issue by xiaobai9978** [LibreService/my_rime#9]
![image](https://user-images.githubusercontent.com/11792557/222372534-a0b06be5-bf5c-464a-9ab6-ba2835f55a20.png)
![image](https://user-images.githubusercontent.com/11792557/222372548-8542fcf9-6fad-4067-82d5-a649b8b96235.png)

![image](https://user-images.githubusercontent.com/11792557/222372839-2e1f6cad-0ef6-4ef9-bd54-53eff51bd97c.png)
![image](https://user-images.githubusercontent.com/11792557/222373092-fe515ee1-d035-47eb-ba51-95cfd8b3c695.png)

我已经成功添加进去了我的输入法，不过我的输入法是用小键盘打字。请问是我操作的问题还是不支持这种输入方式？
非常感谢

**Comment by bczhc** [comment]
我也试验了好久但没有成功。包括让前端发送`KP_[0-9]`这样的代码，但好像librime的key simulation没有支持这种表达，把中前的`_`直接变成破折号`——`了。还有试了schema文件里用于屏蔽大键盘的那些`key_binder`也给去掉了，在桌面端可以用大键盘输入，但在这里大键盘也不管用。

**Comment by xiaobai9978** [comment]
会是因为词库没加载成功吗？

**Comment by eagleoflqj** [comment]
> 会是因为词库没加载成功吗？

如果你使用了`ENABLE_LOGGING=ON`，那F12的控制台可以看到glog的输出，比如luna_pinyin会有
```
I20230302 19:28:10.597999 300364 table.cc:299] loading table file: /build/luna_pinyin.table.bin
```
没什么异常的话加载就没问题。

小键盘不支持肯定是我的问题（因为我是87键用户
我只检查了KeyboardEvent的key，大小键盘的key是一样的，得通过code区分。
好在树莓派78键键盘可以模拟小键盘，我会拿你的输入法测测。

**Comment by bczhc** [comment]
日志里看到了`E20230303 14:27:04.792999 300972 mapped_file.cc:112] attempt to open non-existent file '/build/xiaobai.table.bin'.`，但是检查了`build/librime_native/bin/build/xiaobai.table.bin`，文件是存在的。

**Comment by eagleoflqj** [comment]
文件加载是从`public/ime`，那里肯定没有。因为我做了个错误假设，即每个schemaId对应的文件都以schemaId开头
https://github.com/LibreService/my_rime/blob/a18aa93b474cb56707e25695d327bf37c496ba2b/scripts/install_schemas.mjs#L94-L96
只有rime官方输入法是遵照这个假设的，我得把install_schemas.mjs大修一下

**Comment by eagleoflqj** [comment]
https://github.com/LibreService/my_rime/commit/6e7cabbf7564d9f0fa0d3f0714c62fbfc0c4fa64 解决了词库加载问题。我用来测试的配置如下
```json
[
  {
    "id": "xiaobai_simp",
    "name": "小白T9输入法",
    "emoji": true,
    "target": "xiaobai9978/rime-xiaobai_simp",
    "variants": [],
    "license": "GPL-3.0-only"
  }
]
```
你的输入法有两个问题，一个是不兼容plum，要么按照https://github.com/LibreService/my_rime/issues/8#issuecomment-1451566009 手动把`dicts`复制到`build/librime_native/bin`，要么按https://github.com/bczhc/rime-xiaobai_simp/commit/cd5047994ab5d3bc0f488d857a059e316156eebf 把目录打平；还有就是繁简转换似乎不起作用，所以我给`variants`赋值为`[]`以屏蔽了转换功能。
![Screenshot from 2023-03-04 20-54-13](https://user-images.githubusercontent.com/26783539/222937690-4924b8bd-073d-4f40-a821-6eb9dbff971b.png)

> 好像librime的key simulation没有支持这种表达

感觉是你缺了花括号。现在往URL加上`debug=on`参数可以显示下面的输入框，来直接给librime发key sequence（按回车发送）。

**Comment by eagleoflqj** [comment]
资辞了https://github.com/LibreService/my_rime/commit/73f109b420b40aa5797d40c9070fe6f0b8ff77b5
本来想加个测试，奈何playwright doesn't support numpad https://github.com/microsoft/playwright/issues/15187

**Comment by xiaobai9978** [comment]
成功了，非常感谢
